name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
    - name: Checking the repository
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Assignment_2/dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-go:latest
      continue-on-error: false
    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "Image build result for ${{ github.repository }}"
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: |
          Result is ${{ job.status }}
          Commit: ${{ github.sha }}
